AWSTemplateFormatVersion: 2010-09-09

Description: Stack que despliega una tabla de Dynamo

Parameters:
  NombreTablaDynamo:
    Description:  Nombre de la tabla de DynamoDB
    Type:         String
  CapacidadLectura:
    Description:  Capacidad de lectura de DynamoDB
    MaxValue:     10
    MinValue:     1
    Type:         Number
  CapacidadEscritura:
    Description:  Capacidad de escritura de DynamoDB
    MaxValue:     10
    MinValue:     1
    Type:         Number

Resources:
  TablaDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        -
          AttributeName:  ID
          AttributeType:  S
      BillingMode: PROVISIONED
      KeySchema: 
        - 
          AttributeName:  ID
          KeyType:        HASH
      ProvisionedThroughput:
        ReadCapacityUnits:  !Ref CapacidadLectura
        WriteCapacityUnits: !Ref CapacidadEscritura
      TableClass: STANDARD
      TableName:  !Ref NombreTablaDynamo