AWSTemplateFormatVersion: 2010-09-09

Description: Nested Stack Dynamo

Parameters:
  NombreTablaDynamo:
    Description:  Nombre de la tabla de DynamoDB
    Type:         String

Resources:
  TablaDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        -
          AttributeName:  ID
          AttributeType:  S
      BillingMode: PROVISIONED
      KeySchema: 
        - 
          AttributeName:  ID
          KeyType:        HASH
      ProvisionedThroughput:
        ReadCapacityUnits:  1
        WriteCapacityUnits: 1
      TableClass: STANDARD
      TableName:  !Ref NombreTablaDynamo

Outputs:
  ArnTablaDynamo:
    Description:  ARN de la tabla de Dynamo
    Value:        !GetAtt TablaDynamo.Arn
    Export:
      Name: !Sub ${AWS::StackName}-dynamo