AWSTemplateFormatVersion: 2010-09-09

Description: Introduccion a CloudFormation

Resources:
  TablaDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        -
          AttributeName:  ID
          AttributeType:  S
      BillingMode: PROVISIONED
      KeySchema: 
        - 
          AttributeName:  ID
          KeyType:        HASH
      ProvisionedThroughput:
        ReadCapacityUnits:  1
        WriteCapacityUnits: 1
      TableClass: STANDARD
      TableName:  #Nombre#