AWSTemplateFormatVersion: 2010-09-09

Description: Stack que despliega una tabla de Dynamo

Parameters:
  NombreTablaDynamo:
    Description:  Nombre de la tabla de DynamoDB
    Type:         String

Resources:
  TablaDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        -
          AttributeName:  ID
          AttributeType:  S
      BillingMode: PROVISIONED
      KeySchema: 
        - 
          AttributeName:  ID
          KeyType:        HASH
      ProvisionedThroughput:
        ReadCapacityUnits:  1
        WriteCapacityUnits: 1
      TableClass: STANDARD
      TableName:  !Ref NombreTablaDynamo

Outputs:
  NombreTablaDynamo:
    Description: Nombre de la tabla de DynamoDB
    Export:
      Name: !Sub ${AWS::StackName}-nombre-tabla
    Value:  !Ref TablaDynamo