AWSTemplateFormatVersion: 2010-09-09

Description: Stack que despliega un bucket de S3

Parameters:
  NombreBucket:
    Description:  Nombre del bucket
    Type:         String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-${NombreBucket}

Outputs:
  SalidaNombreBucket:
    Description:  Nombre del bucket
    Value:        !Ref Bucket
    Export:
      Name: !Sub ${AWS::StackName}-bucket