AWSTemplateFormatVersion: 2010-09-09

Description: Stack que despliega un bucket de S3

Parameters:
  Environment:
    AllowedValues:
      - dev
      - prod
    Description:  Entorno del despliegue
    Type:         String
  NombreBucket:
    Description:  Nombre del bucket
    Type:         String

Conditions:
  EsProduccion: !Equals [ !Ref Environment, prod]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: !If [EsProduccion, Enabled, Suspended]
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-${NombreBucket}